language: node_js
dist: trusty
sudo: false

node_js:
- node

cache:
  yarn: true
  directories:
  - node_modules

addons:
  ssh_known_hosts:
  - ec2-52-57-178-93.eu-central-1.compute.amazonaws.com

install:
- yarn

before_script:
- echo "StrictHostKeyChecking no" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_463215d91ccd_key -iv $encrypted_463215d91ccd_iv -in bosstimerbot.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa

script: |
  rsync -a "$PWD/" ec2-user@ec2-52-57-178-93.eu-central-1.compute.amazonaws.com:/app/
  echo 'cd /app && (kill `cat node.pid` || true) && nohup yarn start & echo $! > node.pid' | ssh ec2-user@ec2-52-57-178-93.eu-central-1.compute.amazonaws.com
